contrail_configuration:
  CLOUD_ORCHESTRATOR: kubernetes
  CONTRAIL_VERSION: 5.0.1-0.214
  CONTROLLER_NODES: 172.16.0.89
  CONTROL_NODES: 172.16.0.89
  ENCAP_PRIORITY: MPLSoUDP,MPLSoGRE,VXLAN
  UPGRADE_KERNEL: true
global_configuration:
  CONTAINER_REGISTRY: hub.juniper.net/contrail
  CONTAINER_REGISTRY_USERNAME: JNPR-FieldUser57
  CONTAINER_REGISTRY_PASSWORD: EUp8dSWKeTkY4NhxtyF2
roles:
  gateway:
    contrail_configuration:
      PHYSICAL_INTERFACE: eth1
      VROUTER_AGENT__DEFAULT__gateway_mode: server
multicloud_configuration:
  PATH_CONFIG: &PATH_CONFIG "/etc/multicloud"
  PATH_SSL_CONFIG_LOCAL: "~/.multicloud/ssl"
  PATH_SSL_CONFIG: !join [*PATH_CONFIG, /ssl]
  PATH_OPENVPN_CONFIG: !join [*PATH_CONFIG, /openvpn]
  PATH_BIRD_CONFIG: !join [*PATH_CONFIG, /bird]
  PATH_STRONGSWAN_CONFIG: !join [*PATH_CONFIG, /strongswan]
  PATH_VRRP_CONFIG: !join [*PATH_CONFIG, /vrrp]
  PATH_AWS_CONFIG: !join [*PATH_CONFIG, /aws]
  PATH_INTERFACE_CONFIG: "/etc/network/interfaces.d"
  PATH_FW_CONFIG: !join [*PATH_CONFIG, /firewall]
  PATH_GCP_CONFIG: !join [*PATH_CONFIG, /gcp]
  PATH_SECRET_CONFIG: !join [*PATH_CONFIG, /secret]

  CONTAINER_REGISTRY: "hub.juniper.net/contrail"
  CONTRAIL_MULTICLOUD_VERSION: 5.0.1-0.214

  #UPGRADE_KERNEL: True
  #KERNEL_VERSION: 3.10.0-862.3.2.el7.x86_64

  AS: 65000
  vpn_lo_network: 100.65.0.0/16
  vpn_network: 100.64.0.0/16

  openvpn_port: 443

  bfd_interval: 200ms
  bfd_multiplier: 5
  bfd_interval_multihop: 500ms
  bfd_multiplier_multihop: 5
  core_bgp_secret: bgp_secret
